services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: n8n_postgres
    restart: unless-stopped
#    ports:
#      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CGqz3Kf8
      - POSTGRES_DB=n8n
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d n8n"]
      interval: 2s
      timeout: 5s
      retries: 10
  minio:
    image: minio/minio:latest
    container_name: n8n_minio
    restart: unless-stopped
#    ports:
#      - 9000:9000
#      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=CGqz3Kf8
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9000
    command: server /data --console-address ":9001"
    volumes:
        - ./data/minio:/data
  redis:
    image: redis:7-alpine
    container_name: n8n_redis
    restart: unless-stopped
#    ports:
#      - 6379:6379
    environment:
      - REDIS_PASSWORD=CGqz3Kf8
    command: /bin/sh -c 'redis-server --save 60 1 --loglevel warning --requirepass $${REDIS_PASSWORD}'
    volumes:
      - ./data/redis:/data
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_n8n
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=CGqz3Kf8
      - DB_POSTGRESDB_DATABASE=n8n
      - N8N_ENCRYPTION_KEY=4YmaxKNa497if9w3I5vjfcbSgmkkJkVA
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_REINSTALL_MISSING_PACKAGES=true
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_LOG_LEVEL=info
      - N8N_LOG_FILE_SIZE_MAX=16
      - N8N_LOG_FILE_COUNT_MAX=2
      - N8N_MFA_ENABLED=false
      - N8N_HIDE_USAGE_PAGE=true
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - NODE_ENV=production
      - N8N_CONCURRENCY_PRODUCTION_LIMIT=10
      - N8N_EDITOR_BASE_URL=http://localhost:5678
